// client/src/views/CreateRoom.vue
<script setup lang="ts">
import { ref } from 'vue';
import { useRouter } from 'vue-router';
import { useBackend } from '@/helpers/backend';

const roomName = ref('');
const token = ref('');

const backend = useBackend();

async function createRoom() {
    if (!roomName.value) {
        return;
    }

    const response = await backend.post('/room/create', { roomName: roomName.value });
    if (response.status !== 201) {
        return;
    }

    const room = response.data;
    token.value = room.room_id;
}
</script>

<template>
    <h1>Create Room</h1>
    <input v-model="roomName" type="text" name="room-name" id="room-name">
    <button @click="createRoom">Create Room</button>
    <p>{{ token }}</p>
</template>

// web-frontend/src/pages/CreateRoom.tsx
import { FC } from "react";

export const CreateRoom: FC = () => {

    function createRoom() {
        const name = (document.getElementById("name") as HTMLInputElement).value;
        fetch("http://localhost:3000/room/create", {
            method: "POST",
            body: JSON.stringify({ name: name }),
            headers: {
                "Content-Type": "application/json"
            }
        }).then(async (response: Response) => {
            if (response.ok) {
                const room = Room.fromJson(await response.json());
                document.getElementById("output")!.innerText = `${room.name}: ${room.id}`;
            }
        });
    }

    return (
        <>
            <h1>Create Room</h1>
            <input type="text" name="name" id="name" />
            <button onClick={createRoom}>Create new room</button>
            <p id="output"></p>
        </>
    )
};
